# Generated by Django 4.2.3 on 2023-07-10 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_post_no_of_likes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LikeCommentPost',
            new_name='LikePost',
        ),
    ]
