# Generated by Django 4.2.3 on 2023-07-14 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_followerscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='username',
            field=models.CharField(default=int, max_length=100),
            preserve_default=False,
        ),
    ]
