# Generated by Django 4.2.3 on 2023-07-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_post_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default=str, max_length=100),
            preserve_default=False,
        ),
    ]
