# Generated by Django 4.2.3 on 2023-07-15 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_profile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='following',
            new_name='followings',
        ),
    ]
